@startuml

' View Implementations
class SignView implements SignatureViewInterface {
}

class VerifyView implements SignatureViewInterface {
}

class GenerateKeysView {
}

class MainMenuView {
}

' Controller Classes
class SignatureBaseController {
  signView : SignView
  verifyView : VerifyView
  signatureModel : SignatureModel
  + SignatureBaseController(mainController : MainController)

}
class MainController {
    -Stage primaryStage
    -MainMenuView mainMenuView
    -SignatureBaseController SignatureBaseController
    -GenController genController
    +showMainMenuView(): void
}

class GenController {
  genView : GenView
  genModel : GenModel
  + GenController(mainController : MainController)
}

class GenRSA {
}

' Model Classes
class SignatureModel {
  currentSignatureScheme : SigSchemeInterface
  key : Key
  currentType : SignatureType
}

class GenerateKeysModel {
  keySize : int
  currentGen : GenRSA
  generatedKeyPair : KeyPair
}

' Enum and Factory
enum SigType {
  RSASSA_PKCS1_v1_5
  ANSI_X9_31_RDSA
  ISO_IEC_9796_2_SCHEME_1
}

class SchemeFactory {
    +createScheme(type: SigType): SigSchemeInterface
}

interface SigSchemeInterface {
  sign(M : byte[]) : byte[]
  verify(M : byte[], signature : byte[]) : boolean
}

class SigScheme implements SigSchemeInterface {
}

class RSASSA_PKCS1_v1_5 extends SigScheme {
}

class ANSI_X9_31_RDSA extends SigScheme {
}

class ISO_IEC_9796_2_SCHEME_1 extends SigScheme {
}


' Relationships
SignatureBaseController --> SignView
SignatureBaseController --> VerifyView
SignatureBaseController <.. SignView
SignatureBaseController <.. VerifyView
SignatureBaseController --> SignatureModel
GenController --> GenerateKeysModel
GenController --> GenerateKeysView
GenController <.. GenerateKeysView
MainController --> MainMenuView
MainController <.. MainMenuView
MainController o-- SignatureBaseController
MainController o-- GenController
SchemeFactory --> SigType: uses
SchemeFactory --> SigSchemeInterface: creates
SignatureModel --> SchemeFactory
GenerateKeysModel o-- GenRSA



@enduml
